# Generated by Django 4.1.2 on 2022-10-26 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(10)]),
        ),
    ]
