# Generated by Django 4.1.2 on 2022-10-30 11:45

import accounts.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(choices=[('a', 'Admin'), ('t', 'Teacher')], default='t', max_length=1)),
                ('status', models.CharField(choices=[('p', 'pending'), ('a', 'Accepted'), ('r', 'Rejected'), ('b', 'Blocked')], default='p', max_length=1)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='users/requests', validators=[accounts.validators.validate_file_size])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
