# Generated by Django 4.1.2 on 2022-10-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
