# Generated by Django 4.0.4 on 2022-11-03 07:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5000), django.core.validators.MinValueValidator(10)])),
                ('published', models.BooleanField(default=False)),
                ('difficulty', models.CharField(choices=[('b', 'Beginner'), ('i', 'Intermediate'), ('a', 'Advance')], default='b', max_length=1)),
                ('time', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('token', models.CharField(max_length=15, unique=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
